import React from 'react';
import Content from '@theme-init/DocItem/Content';
import { useDoc } from '@docusaurus/plugin-content-docs/client';
import CopyPage from '../../../components/CopyPage';

// Pages generated by docusaurus-plugin-openapi-docs have their own layout and
// don't turn into readable Markdown.
function isGeneratedApiPage(source) {
  return /\.(api|info|tag|schema)\.mdx$/.test(source);
}

export default function ContentWrapper(props) {
  const { metadata, frontMatter } = useDoc();
  return (
    <>
      {!frontMatter.hide_page_actions && !isGeneratedApiPage(metadata.source) && (
        <CopyPage permalink={metadata.permalink} title={metadata.title} />
      )}
      <Content {...props} />
    </>
  );
}
